config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'offers#index'

  devise_for :users

  resources :users do
    scope(path_names: { index: 'parcours' }) do
      resources :assignments, path: 'parcours'
    end
  end

  scope(path_names: { show: 'formation' }) do
    resources :learnings, path: 'formation'
  end

  resources :user_companies

  scope(path_names: { show: 'entreprise' }) do
    resources :companies, path: 'entreprise' do
      get :learnings, on: :member
      get :offers, on: :member
      get :users, on: :member
    end
  end

  resources :contacts, only: %i[new create] do
    get '/thanks' => 'contacts#thanks'
  end
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :learning
  belongs_to :user

  after_create :inscription_send, :slack_new_assignment
  after_update :validation_send, :slack_validation_assignment

  def inscription_send
    UserMailer.new_assignment_email(self).deliver_now
  end

  def validation_send
    UserMailer.validation_assignment_email(self).deliver_now
  end

  def slack_new_assignment
    begin
      slack_notifier(self.user.company.webhook, self.user.company.channel).ping "Hello #{self.user.email}, La formation #{self.learning.name} est disponible sur ton espace Zorya ! Connecte toi directement sur ton compte."
    rescue => exception
    end
  end

  def slack_validation_assignment
    begin
      slack_notifier(self.user.company.webhook, self.user.company.channel).ping "Bien joué #{self.user.mail} ! La formation #{self.learning.name} a bien été validée."
    rescue => exception
    end
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :sign_out
  def index
    @assignments = Assignment.all
  end

  def new
    @assignment = Assignment.new
  end

  def create
    @user = User.find(params[:user_id])
    @learning = Learning.find(params[:learning_id])
    @assignments = Assignment.all
    @list_assignment_of_user_id = []
    @list_assignment_of_learning_id = []

    @assignments.each do |assignment|
      @list_assignment_of_user_id << assignment.user_id
      @list_assignment_of_learning_id << assignment.learning_id
    end

    if @list_assignment_of_user_id.include?(@user.id) && @list_assignment_of_learning_id.include?(@learning.id)
      flash[:danger] = 'Cet utilisateur est déjà inscrit à cette formation.'
    else
      @assignment = Assignment.create(user_id: @user.id, learning_id: @learning.id)

      respond_to do |format|
        format.html { redirect_to company_path, notice: 'inscription réussie' }
        format.js {}
      end
    end
  end

  def update
    @assignment = Assignment.find(params[:id])
    if @assignment.update(assignment_done: DateTime.current.to_date)
      redirect_to user_assignments_path(current_user.id)
    else
      flash.now[:alert] = @assignment.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @learning = Learning.find(params[:learning_id])
    @assignment = Assignment.find(params[:id])
    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to company_path, notice: 'Désinscription réussie' }
      format.js {}
    end
  end

  private

  def sign_out
    redirect_to root_path unless user_signed_in?
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_inscription_button.html.erb
<%if @user.learnings.include?(@learning)%>
  <%= button_to "désinscrire", user_assignment_path(@user.id, 
              @assignments.find_by(user_id: @user.id, learning_id: @learning.id)), remote: true, data: { confirm: "Êtes-vous sûr(e) ?" }, params: {user_id: @user.id, learning_id: @learning.id}, method: :delete, class: "btn btn-secondary" %>
<% else %>
  <%= button_to 'inscrire', user_assignments_path(@user.id), remote: true, params: {user_id: @user.id, learning_id: @learning.id} ,method: :post, class: "btn btn-primary" %>
<% end %>

app/views/assignments/create.js.erb
<%= id = "inscription_button_#{@learning.id}_#{@user.id}" %>
document.getElementById("<%= id %>").innerHTML = "<%= j render 'inscription_button', user: @user, learning:@learning %>";

app/views/assignments/destroy.js.erb
<%= id = "inscription_button_#{@learning.id}_#{@user.id}" %>
document.getElementById("<%= id %>").innerHTML = "<%= j render 'inscription_button', user: @user, learning:@learning %>";

app/views/assignments/index.html.erb
<h2 class="text-center mb-5">Mes formations</h2>
<div class=" d-flex flex-row justify-content-between flex-wrap">
  <% @assignments.each do |assignment|%>
    <% if current_user.assignments.include?(assignment) %>
      <div class="card" style="width: 18rem;">
        <%= image_tag(assignment.learning.photo , class: 'card-img-top', alt: 'package-photo') %>
        <div class="card-body">
          <h5 class="card-title text-center mb-4"><%= assignment.learning.name %></h5>
          <div class="d-flex flex-row justify-content-around mb-4">
            <p class="btn btn-primary mt-2"><%= link_to "Voir le cours", learning_path(assignment.learning.id), params:{assignment_id: assignment.id} %></p>
            <% if assignment.assignment_done? %>
              <i class="bi bi-check-circle fa-2x text-primary mt-2 text-success"></i>
            <% else %>
              <i class="bi bi-circle fa-2x text-primary mt-2"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <% if current_user.assignments.length == 0 %>
    <div class="section-user-infos mb-5">
      <div class="user-infos-1 d-flex flex-row flex-wrap">
        <p>Tu n'as pas de formation disponible pour le moment. Soit rassuré tu recevras une notification ou un email lorsqu'une nouvelle formation sera disponible.</p>
      </div>
    </div>
  <% else %>
  <% end %>
</div>