config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'offers#index'

  devise_for :users

  resources :users do
    scope(path_names: { index: 'parcours' }) do
      resources :assignments, path: 'parcours'
    end
  end

  scope(path_names: { show: 'formation' }) do
    resources :learnings, path: 'formation'
  end

  resources :user_companies

  scope(path_names: { show: 'entreprise' }) do
    resources :companies, path: 'entreprise' do
      get :learnings, on: :member
      get :offers, on: :member
      get :users, on: :member
    end
  end

  resources :contacts, only: %i[new create] do
    get '/thanks' => 'contacts#thanks'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_company
  has_one :company, through: :user_company
  has_many :assignments
  has_many :learnings, through: :assignments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true,
                    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Veuillez saisir un email valide s'il vous plaît." }

  validate :password_complexity

  enum status: {
    user: 0,
    customer: 1,
    administrator: 2
  }, _prefix: true

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def password_complexity
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/

    errors.add :password,
               'Votre mot de passe doit contenir minimum 8 caractères, 1 majuscule, 1 minuscule, 1 chiffre et 1 caractère spécial (#?!@$%^&*-).'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :sign_out
  def show
    @user = User.find(current_user.id)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)

    if @user.update(first_name: params[:user][:first_name], last_name: params[:user][:last_name])
      @user.save
      flash[:succes] = 'Vos informations ont bien été mises à jour'
      redirect_to user_path(current_user.id)
    else
      flash[:danger] = 'Des informations sont manquantes'
      redirect_to user_path(current_user.id)
    end
  end

  private

  def sign_out
    redirect_to root_path unless user_signed_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<section class="section-form-devise">
  <h2>Modifier mon profil</h2>
  <div class="form-devise">
    <%= form_for @user do |f| %>
      <div class='d-flex flex-column'>
        <label> Nom de famille</label>
        <%= f.text_area :last_name, autofocus: true, autocomplete: "last_name", class: 'fill-field' %>
      </div>
      <div class='d-flex flex-column'>
        <label> Prénom </label>
        <%= f.text_area :first_name, autofocus: true, autocomplete: "first_name", class: 'fill-field' %>
      </div>
      <div class='d-flex flex-column align-self-center'>
        <%= button_tag( :class => "btn btn-primary", :type => "submit" ) do %>Mettre à jour
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/users/show.html.erb
<!-- UPS user -->
<div id="usp-section" class="row align-items-center mb-5 pb-5">
  <div class="d-flex col-md align-items-center border-bottom border-md-0 mb-16pt mb-md-0 pb-16pt pb-md-0">
    <div class="rounded-circle bg-primary w-64 h-64 d-inline-flex align-items-center justify-content-center mr-16pt">
      <i class="bi bi-book text-white icon-24pt"></i>
    </div>
    <div class="flex">
      <div class="card-title mb-4pt">Choix du format</div>
      <p class="card-subtitle text-70">Nos cours sont disponibles au format texte ou vidéo, choisissez ce qui vous convient.</p>
    </div>
  </div>
  <div class="d-flex col-md align-items-center border-bottom border-md-0 mb-16pt mb-md-0 pb-16pt pb-md-0">
    <div class="rounded-circle bg-primary w-64 h-64 d-inline-flex align-items-center justify-content-center mr-16pt">
      <i class="bi bi-patch-check-fill text-white icon-24pt"></i>
    </div>
    <div class="flex">
      <div class="card-title mb-4pt">Fait par des experts</div>
      <p class="card-subtitle text-70">Toutes nos formations ont été réalisées par des experts en cybersécurité.</p>
    </div>
  </div>
  <div class="d-flex col-md align-items-center">
    <div class="rounded-circle bg-primary w-64 h-64 d-inline-flex align-items-center justify-content-center mr-16pt">
      <i class="bi bi-clock-history text-white icon-24pt"></i>
    </div>
    <div class="flex">
      <div class="card-title mb-4pt">Accés illimité</div>
      <p class="card-subtitle text-70">Cours et ressources disponibles en illimité et à vie.</p>
    </div>
  </div>
</div>
<!-- UPS user end -->
<!-- INFOS -->
<h2 class="text-center">Informations personnelles:</h2>
<div class="section-user-infos mb-5">
  <div class="user-infos-1 d-flex flex-row flex-wrap">
    <div class="user-avatar"><%= image_tag('whiteUser.svg', class: 'user-avatar-img', alt: 'logo') %></div>
    <div class="user-h4">
      <span class="user-span">
        <h4>Nom :</h4>
        <p><%= @user.last_name %></p>
      </span>
      <span class="user-span">
        <h4>Prénom :</h4>
        <p><%= @user.first_name %></p>
      </span>
      <span class="user-span">
        <h4>Email :</h4>
        <p><%= @user.email %></p>
      </span>
      <% if @user.company.nil? %>
        <div class="no-compagny-p">
          <p><i>Vous n'êtes actuellement rattaché à aucune entreprise. Vous êtes un collaborateur? Veuillez contacter votre responsable pour le rattachement. Vous êtes le responsable? Veuillez prendre contact avec votre Gestionnaire ou nous contacter pour souscrire à une offre.</i></p>
          <p id="btn-user-infos" class="btn btn-primary"><%= link_to "Nous contacter", new_contact_path()%></p>
        </div>
      <%else%>
        <span class="user-span">
          <h4>Entreprise :</h4>
          <p><%= @user.company.name %></p>
        </span>
      <% end %>
    </div>
  </div>
  <div class="user-infos-2">
  </div>
  <hr>
  <div class="section-btn-infos">
    <p id="btn-user-infos" class="btn btn-secondary-outline"><%= link_to "Modifier mes informations de connexion",  edit_user_registration_path %></p>
    <p id="btn-user-infos" class="btn btn-secondary-outline"><%= link_to "Modifier mon nom",  edit_user_path(current_user.id) %></p>
    <p id="btn-user-infos" class="btn btn-primary"><%= link_to "Voir mes parcours",  user_assignments_path(@user.id) %></p>
  </div>
</div>
<!-- INFOS END -->