config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'offers#index'

  devise_for :users

  resources :users do
    scope(path_names: { index: 'parcours' }) do
      resources :assignments, path: 'parcours'
    end
  end

  scope(path_names: { show: 'formation' }) do
    resources :learnings, path: 'formation'
  end

  resources :user_companies

  scope(path_names: { show: 'entreprise' }) do
    resources :companies, path: 'entreprise' do
      get :learnings, on: :member
      get :offers, on: :member
      get :users, on: :member
    end
  end

  resources :contacts, only: %i[new create] do
    get '/thanks' => 'contacts#thanks'
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :purchases
  has_many :user_companies
  has_many :users, through: :user_companies
  has_many :offers, through: :purchases
  has_many :learnings, through: :offers
  has_many :assignments, through: :users

  validates :name, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :customer_or_administrator
  def show
    @company = Company.find(params[:id])
    if current_user.company != @company
      flash[:danger] = "Vous n'avez pas accès à cette page"
      redirect_to root_path
    end
    @users = @company.users
    @learnings = @company.learnings
    @assignments = Assignment.all
    @offers = Offer.all
    @user_companies = UserCompany.all
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(channel: params[:company][:channel], webhook: params[:company][:webhook])
      @company.save
      flash[:success] = 'Vos informations ont bien été enregistrées'
      redirect_to company_path(params[:id])
    else
      flash[:danger] = 'Des informations sont manquantes'
      redirect_to company_path(params[:id])
    end
  end

  def learnings
    @company = Company.find(params[:id])
    @learnings = @company.learnings
    @users = @company.users
    @assignments = Assignment.all

    respond_to do |format|
      format.html { redirect_to company_path }
      format.js
    end
  end

  def offers
    @company = Company.find(params[:id])
    @learnings = @company.learnings
    @users = @company.users
    @offers = Offer.all
    @assignments = Assignment.all

    respond_to do |format|
      format.html { redirect_to company_path }
      format.js
    end
  end

  def users
    @company = Company.find(params[:id])
    @learnings = @company.learnings
    @users = @company.users
    @offers = Offer.all
    @assignments = Assignment.all
    @user_companies = UserCompany.all

    respond_to do |format|
      format.html { redirect_to company_path }
      format.js
    end
  end

  private

  def customer_or_administrator
    if user_signed_in?
      unless current_user.status_customer? || current_user.status_administrator?
        flash[:danger] = "Vous n'avez pas accès à cette page"
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def in_words(int)
    numbers_to_name = {
      1_000_000 => 'million',
      1000 => 'thousand',
      100 => 'hundred',
      90 => 'ninety',
      80 => 'eighty',
      70 => 'seventy',
      60 => 'sixty',
      50 => 'fifty',
      40 => 'forty',
      30 => 'thirty',
      20 => 'twenty',
      19 => 'nineteen',
      18 => 'eighteen',
      17 => 'seventeen',
      16 => 'sixteen',
      15 => 'fifteen',
      14 => 'fourteen',
      13 => 'thirteen',
      12 => 'twelve',
      11 => 'eleven',
      10 => 'ten',
      9 => 'nine',
      8 => 'eight',
      7 => 'seven',
      6 => 'six',
      5 => 'five',
      4 => 'four',
      3 => 'three',
      2 => 'two',
      1 => 'one'
    }
    str = ''
    numbers_to_name.each do |num, name|
      if int == 0
        return str
      elsif int.to_s.length == 1 && int / num > 0
        return str + name.to_s
      elsif int < 100 && int / num > 0
        return str + name.to_s if int % num == 0

        return str + name.to_s + in_words(int % num)
      elsif int / num > 0
        return str + in_words(int / num) + name.to_s + in_words(int % num)
      end
    end
  end
end

app/views/companies/_company_learnings.html.erb
<div class="d-flex flex-column flex-wrap" id="card-collapse">
  <div class="accordion" id="accordionExample">
    <% @learnings.each_with_index do |learning, i| %>
      <div class="card">
        <div class="card-header" id="heading<%= in_words(i+1)%>">
          <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse<%= in_words(i+1)%>" aria-expanded="true" aria-controls="collapse<%= in_words(i+1)%>">
              <%= learning.name %>&nbsp;&nbsp;&nbsp;<i class="bi bi-chevron-compact-down"></i>
            </button>
            <hr class="">
          </h2>
        </div>
        <div id="collapse<%= in_words(i+1)%>" class="collapse" aria-labelledby="heading<%= in_words(i+1)%>" data-parent="#accordionExample">
          <div class="card-body">
            <div class="compagny-learning-each d-flex flex-row justify-content-center">
              <% @users.each do |user| %>
                <p class="learning-user-mail text-center"><%= user.email %>
                  <div id= "inscription_button_<%= learning.id %>_<%= user.id %>" class="d-flex justify-content-center">
                    <%if user.learnings.include?(learning)%>
                      <%= button_to "désinscrire", user_assignment_path(user.id, 
                        @assignments.find_by(user_id: user.id, learning_id: learning.id)), remote: true, data: { confirm: "Êtes-vous sûr(e) ?" }, params: {user_id: user.id, learning_id: learning.id}, method: :delete, class: "btn btn-secondary" %>
                    <% else %>
                      <%= button_to 'inscrire', user_assignments_path(user.id), remote: true, params: {user_id: user.id, learning_id: learning.id} ,method: :post, class: "btn btn-primary" %>
                    <% end %>
                  </div>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/companies/_company_offers.html.erb
<div class="d-flex flex-column" id="card-collapse">
  <div class="accordion" id="accordionExample">
    <% @offers.each_with_index do |offer, i| %>
      <div class="card">
        <div class="card-header" id="heading<%= in_words(i+1)%>">
          <h2 class="mb-0">
            <% if @company.offers.include?(offer) %>
              <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse<%= in_words(i+1)%>" aria-expanded="true" aria-controls="collapse<%= in_words(i+1)%>">
                <%= offer.name %>&nbsp;&nbsp;&nbsp;<i class="bi bi-check-circle fa-1x text-success"></i>&nbsp;&nbsp;&nbsp;<i class="bi bi-chevron-compact-down"></i>
              </button>
            <% else %>
              <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse<%= in_words(i+1)%>" aria-expanded="true" aria-controls="collapse<%= in_words(i+1)%>">
                <%= offer.name %>&nbsp;&nbsp;&nbsp;<i class="bi bi-x-circle fa-1x text-danger"></i>&nbsp;&nbsp;&nbsp;<i class="bi bi-chevron-compact-down"></i>
              </button>
            <% end %>
            <hr class="">
          </h2>
        </div>
        <div id="collapse<%= in_words(i+1)%>" class="collapse" aria-labelledby="heading<%= in_words(i+1)%>" data-parent="#accordionExample">
          <div class="card-body">
            <p class="card-text"><%= offer.description %></p>
            <p class="card-text">Le pack comprend les formations suivantes :</p>
            <p><% offer.learnings.each do |learning| %></p>
              <p>○ <%= learning.name %></p>
            <% end %>
          </div>
          <% if @company.offers.include?(offer) %>
            <div class="d-flex flex-row justify-content-around mb-4">
              <p class="btn btn-primary"><%= link_to "Gérer mes formations", learnings_company_path, method: :get,  remote: true%></p>
            </div>
          <% else %>
            <div class="d-flex flex-row justify-content-around mb-4">
              <p class="btn btn-primary"><%= link_to "Nous contacter", new_contact_path()%></p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/companies/_company_user.html.erb
  <div id= "user_list" class="">
  <% @users.each do |user| %>
    <% if user == current_user %>
    <% else %>
      <div id= "user_<%= user.id %>" class="">
        <h5>Utilisateur: <%= user.email %></h5>
        <div>
          <%= button_to "retirer de ma société", user_company_path(@user_companies.find_by(user_id: user.id, company_id: @company.id)), remote: true, data: { confirm: "Êtes-vous sûr(e) ?" }, params: {user_id: user.id, company_id: @company.id}, method: :delete, class: "form-btn" %>
        </div>
        <hr class="">
      </div>
    <% end %>
  <% end %>
</div>
<div>
  <span>Ajouter un user</span>
  <%= form_tag user_companies_path, method: 'post', remote: true do %>
    <%= hidden_field_tag :company_id , @company.id  %>
    <%= email_field_tag 'email', nil, class: 'fill-field' %>
    <%= button_tag( :class => "btn btn-secondary", :type => "submit" ) do %> Ajouter
                                <% end %>
  <% end %>
</div>

app/views/companies/_company_users.html.erb
<div class="d-flex flex-column">
  <div>
    <span>Ajouter un utilisateur</span>
    <%= form_tag user_companies_path, method: 'post', remote: true do %>
      <%= hidden_field_tag :company_id , @company.id  %>
      <%= email_field_tag 'email', nil, class: 'fill-field' %>
      <%= button_tag( :class => 'btn btn-primary', :type => "submit" ) do %> Ajouter
      <% end %>
    <% end %>
  </div>
  <div id= "user_list" class="">
    <h5 class="mb-4">UTILISATEURS AJOUTÉS :</h5>
    <% @users.each do |user| %>
      <% if user == current_user %>
      <% else %>
        <div id= "user_<%= user.id %>" class="">
          <span class="d-flex flex-row">
            <p class="email-p-users"><%= user.email %></p>
          </span>
          <div>
            <%= button_to "détacher ce compte", user_company_path(@user_companies.find_by(user_id: user.id, company_id: @company.id)), remote: true, data: { confirm: "Êtes-vous sûr(e) ?" }, params: {user_id: user.id, company_id: @company.id}, method: :delete, class: "btn btn-primary" %>
          </div>
          <hr class="">
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/companies/edit.html.erb
<section class="section-form-devise">
  <div class="form-devise">
    <%= form_for [@company] do |f|%>
      <div class='form-group'>
        <label> Canal Slack </label>
        <%= f.text_area :channel, size: "x1", class: 'form-control' %>
        <label class="mt-2"> Adresse URL du webhook</label>
        <%= f.text_area :webhook, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= button_tag( :class => "btn btn-primary", :type => "submit" ) do %> Envoyer mes informations Slack
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/companies/learnings.js.erb
  <%= id = "company_render" %>
document.getElementById("<%= id %>").innerHTML = ""
document.getElementById("<%= id %>").insertAdjacentHTML("beforeend", "<%= j render 'company_learnings', user: @user, company: @company %>")
document.getElementById("<%= id %>").style.backgroundColor = "#5567ff";

app/views/companies/offers.js.erb
  <%= id = "company_render" %>
document.getElementById("<%= id %>").innerHTML = ""
document.getElementById("<%= id %>").insertAdjacentHTML("beforeend", "<%= j render 'company_offers', user: @user, company: @company %>")
document.getElementById("<%= id %>").style.backgroundColor = "#2936a6";

app/views/companies/show.html.erb
<div class="d-flex flex-column justify-content-center">
  <h2 class="text-center mb-4">Mon espace entreprise</h2>
  <%= link_to 'Paramétrer mon intégration Slack', edit_company_path, method: :get, class: 'btn-slack btn btn-secondary-outline text-light'%>
</div>
<div class="d-flex flex-column justify-content-center">
  <div class="grid-compagny">
    <div id="company_users" class="grid1">
      <%= link_to 'GESTION DES UTILISATEURS', users_company_path, method: :get, id: 'btn1', class: 'btn btn-compagny', remote: true %>
    </div>
    <div id="company_learnings" class="grid2">
      <%= link_to 'ATTRIBUER DES FORMATIONS', learnings_company_path, method: :get, class: 'btn btn-compagny',  remote: true %>
    </div>
    <div id="company_offers" class="grid3">
      <%= link_to 'GERER VOS OFFRES', offers_company_path, method: :get, class: 'btn btn-compagny',  remote: true %>
    </div>
    <div id="company_render" class="grid-render"><%= render 'company_users', class: 'btn btn-compagny' %></div>
  </div>
</div>

app/views/companies/users.js.erb
  <%= id = "company_render" %>
document.getElementById("<%= id %>").innerHTML = ""
document.getElementById("<%= id %>").insertAdjacentHTML("beforeend", "<%= j render 'company_users', user: @user, company: @company %>")
document.getElementById("<%= id %>").style.backgroundColor = "#939eff";