config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'offers#index'

  devise_for :users

  resources :users do
    scope(path_names: { index: 'parcours' }) do
      resources :assignments, path: 'parcours'
    end
  end

  scope(path_names: { show: 'formation' }) do
    resources :learnings, path: 'formation'
  end

  resources :user_companies

  scope(path_names: { show: 'entreprise' }) do
    resources :companies, path: 'entreprise' do
      get :learnings, on: :member
      get :offers, on: :member
      get :users, on: :member
    end
  end

  resources :contacts, only: %i[new create] do
    get '/thanks' => 'contacts#thanks'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :learning
  belongs_to :user

  after_create :inscription_send, :slack_new_assignment
  after_update :validation_send, :slack_validation_assignment

  def inscription_send
    UserMailer.new_assignment_email(self).deliver_now
  end

  def validation_send
    UserMailer.validation_assignment_email(self).deliver_now
  end

  def slack_new_assignment
    begin
      slack_notifier(self.user.company.webhook, self.user.company.channel).ping "Hello #{self.user.email}, La formation #{self.learning.name} est disponible sur ton espace Zorya ! Connecte toi directement sur ton compte."
    rescue => exception
    end
  end

  def slack_validation_assignment
    begin
      slack_notifier(self.user.company.webhook, self.user.company.channel).ping "Bien joué #{self.user.mail} ! La formation #{self.learning.name} a bien été validée."
    rescue => exception
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :purchases
  has_many :user_companies
  has_many :users, through: :user_companies
  has_many :offers, through: :purchases
  has_many :learnings, through: :offers
  has_many :assignments, through: :users

  validates :name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/learning.rb
class Learning < ApplicationRecord
  has_many :offer_learnings
  has_many :assignments
  has_many :offers, through: :offer_learnings
  has_many :users, through: :assignments
  has_one_attached :photo

  validates :name, presence: true
  validates :content, presence: true
  validates :duration, presence: true
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :purchases
  has_many :offer_learnings
  has_many :learnings, through: :offer_learnings
  has_many :companies, through: :purchases
  has_one_attached :photo

  validates :name, presence: true
end

app/models/offer_learning.rb
class OfferLearning < ApplicationRecord
  belongs_to :offer
  belongs_to :learning
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :company
  belongs_to :offer
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_company
  has_one :company, through: :user_company
  has_many :assignments
  has_many :learnings, through: :assignments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true,
                    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Veuillez saisir un email valide s'il vous plaît." }

  validate :password_complexity

  enum status: {
    user: 0,
    customer: 1,
    administrator: 2
  }, _prefix: true

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def password_complexity
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/

    errors.add :password,
               'Votre mot de passe doit contenir minimum 8 caractères, 1 majuscule, 1 minuscule, 1 chiffre et 1 caractère spécial (#?!@$%^&*-).'
  end
end

app/models/user_company.rb
class UserCompany < ApplicationRecord
  belongs_to :user
  belongs_to :company

  after_create :slack_welcome

  def slack_welcome
    slack_notifier(company.webhook,
                   company.channel).ping "Hello #{user.email}, tu viens d'être ajouté au channel Slack de #{company.name}, c'est ici que tu recevras tes notifications pour tes formations Zorya !"
  rescue StandardError => e
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :sign_in

  def index
    @offers = Offer.all
  end

  private

  def sign_in
    redirect_to user_path(current_user.id) if user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :sign_out
  def show
    @user = User.find(current_user.id)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)

    if @user.update(first_name: params[:user][:first_name], last_name: params[:user][:last_name])
      @user.save
      flash[:succes] = 'Vos informations ont bien été mises à jour'
      redirect_to user_path(current_user.id)
    else
      flash[:danger] = 'Des informations sont manquantes'
      redirect_to user_path(current_user.id)
    end
  end

  private

  def sign_out
    redirect_to root_path unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def in_words(int)
    numbers_to_name = {
      1_000_000 => 'million',
      1000 => 'thousand',
      100 => 'hundred',
      90 => 'ninety',
      80 => 'eighty',
      70 => 'seventy',
      60 => 'sixty',
      50 => 'fifty',
      40 => 'forty',
      30 => 'thirty',
      20 => 'twenty',
      19 => 'nineteen',
      18 => 'eighteen',
      17 => 'seventeen',
      16 => 'sixteen',
      15 => 'fifteen',
      14 => 'fourteen',
      13 => 'thirteen',
      12 => 'twelve',
      11 => 'eleven',
      10 => 'ten',
      9 => 'nine',
      8 => 'eight',
      7 => 'seven',
      6 => 'six',
      5 => 'five',
      4 => 'four',
      3 => 'three',
      2 => 'two',
      1 => 'one'
    }
    str = ''
    numbers_to_name.each do |num, name|
      if int == 0
        return str
      elsif int.to_s.length == 1 && int / num > 0
        return str + name.to_s
      elsif int < 100 && int / num > 0
        return str + name.to_s if int % num == 0

        return str + name.to_s + in_words(int % num)
      elsif int / num > 0
        return str + in_words(int / num) + name.to_s + in_words(int % num)
      end
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/learnings_helper.rb
module LearningsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/user_companies_helper.rb
module UserCompaniesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="border-top-2 mt-auto">
  <div class="container page__container page-section d-flex flex-column">
    <p class="text-70 brand mb-24pt">
      <%= image_tag('black-70@2x.png', class: 'brand-icon', alt: 'Luma', width: '30') %>
      Zorya
      <%= link_to '<i id="social-icon" class="bi bi-twitter font-size-20pt"></i>'.html_safe, 'https://twitter.com/ZoryaLearning', target: "_blank", rel: "nofollow" %>
      <%= link_to '<i id="social-icon" class="bi bi-youtube font-size-20pt"></i>'.html_safe, 'https://www.youtube.com/channel/UCWq5Nevszuce7Egn4kDeqQg', target: "_blank", rel: "nofollow" %>
      <%= link_to '<i id="social-icon" class="bi bi-linkedin font-size-20pt"></i>'.html_safe, 'https://www.linkedin.com/in/zorya-learning/', target: "_blank", rel: "nofollow" %>
    </p>
    <p class="measure-lead-max small text-70 mr-8pt">Formez vos collaborateurs à la cybersécurité avec Zorya, votre plateforme e-learning.</p>
    <p class="text-50 small mt-n1 mb-0">Made with ❤️ by Matthias, Iris & Olivia</p>
    <p class="text-50 small mt-n1 mb-0">Copyright Zorya 2022 &copy; Tous droits réservés.</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="jumbotron">
  <h1>Zorya, votre plateforme e-learning</h1>
  <p class="lead">Formez vos employés à la cybersécurité.</p>
  <p class="lead">
    <p class="btn btn-primary btn-lg"><%= link_to "Faire une demande de démo", new_contact_path()%></p>
  </p>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand pr-0 navbar-dark border-bottom-2"
                     id="default-navbar"
                     data-primary>
  <% if !user_signed_in? %>
    <%= link_to root_path, class:"rounded bg-primary" do %>
      <span class=""><%= image_tag('logoZorya.png', class: 'img-fluid', id: 'logo-nav', alt: 'logo') %></span>
    <% end %>
  <% else %>
    <%= link_to root_path,  class:"navbar-brand mr-16pt d-lg-none"  do %>
      <span class="rounded bg-primary"><%= image_tag('logoZorya.png', class: 'img-fluid', id: 'logo-nav', alt: 'logo') %></span>
      <span class="d-none d-lg-block">Luma</span>
    <% end %>
  <% end %>
  <!-- Navbar Brand -->
  <!-- // END Navbar Brand -->
  <!-- Navbar Toggler -->
  <% if user_signed_in? %>
    <%= button_tag( :class => "navbar-toggler w-auto mr-16pt d-block d-lg-none rounded-0", :type => "button", :data_toggle => "sidebar", )  do %>
      <%= link_to "Mes formations", user_assignments_path(current_user.id), class: "sidebar-link" %>
    <% end %>
    <% if current_user.status_customer? %>
      <%= button_tag( :class => "navbar-toggler w-auto mr-16pt d-block d-lg-none rounded-0", :type => "button", :data_toggle => "sidebar") do %>
        <%= link_to "Mon espace entreprise", company_path(current_user.company.id), class: "sidebar-link" %>
      <% end %>
    <% end %>
    <% if current_user.status_administrator? %>
      <%= button_tag( :class => "navbar-toggler w-auto mr-16pt d-block d-lg-none rounded-0", :type => "button", :data_toggle => "sidebar") do %>
        <%= link_to "Mon espace entreprise", company_path(current_user.company.id), class: "sidebar-link" %>
      <% end %>
      <%= button_tag( :class => "navbar-toggler w-auto mr-16pt d-block d-lg-none rounded-0", :type => "button", :data_toggle => "sidebar") do %>
        <%= link_to "Administrer Zorya", rails_admin_path(), class: "sidebar-link" %>
      <% end %>
    <% end %>
  <% else %>
  <% end %>
  <!-- // END Navbar Toggler -->
  <div class="flex"></div>
  <!-- Navbar Menu -->
  <div class="nav navbar-nav flex-nowrap d-flex mr-16pt">
    <div class="nav-item dropdown">
      <a href="#"
                               class="nav-link d-flex align-items-center dropdown-toggle"
                               data-toggle="dropdown"
                               data-caret="false">
        <span class="avatar avatar-sm mr-8pt2">
          <span class="avatar-title rounded-circle bg-primary"><i class="bi bi-person-fill font-size-20pt"></i></span>
        </span>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-header"><strong>Mon compte</strong></div>
        <% if user_signed_in? %>
          <%= link_to "Modifier mon profil", edit_user_registration_path, class: " uppercase dropdown-item" %>
          <%= link_to "Se déconnecter",  destroy_user_session_path, class: " uppercase dropdown-item" %>
        <% else %>
          <%= link_to "S'inscrire", new_user_registration_path, class: "uppercase dropdown-item" %>
          <%= link_to "Se connecter", new_user_session_path, class: " uppercase dropdown-item" %>
        <% end %>
      </div>
    </div>
  </div>
  <!-- // END Navbar Menu -->
</div>

app/views/layouts/_profile_header.html.erb
<div class="jumbotron">
  <% if user_signed_in? && current_user.first_name != nil %>
    <h1 class="text-center"><%= current_user.first_name %>,<br>
      Bienvenue sur Zorya, votre plateforme e-learning.</h1>
  <% else %>
    <h1>Bienvenue sur Zorya, votre plateforme e-learning</h1>
  <% end %>
</div>

app/views/layouts/_sidebar.html.erb
<div class="mdk-drawer js-mdk-drawer"
                 id="default-drawer">
  <div class="mdk-drawer__content">
    <div class="sidebar sidebar-black-dodger-blue sidebar-left"
                         data-perfect-scrollbar>
      <!-- Sidebar Content -->
      <%= link_to root_path,  class:"sidebar-brand"  do %>
        <span class="avatar avatar-xl sidebar-brand-icon h-auto">
          <div class="rounded bg-primary"><%= image_tag('logoZorya.png', class: 'img-fluid', alt: 'logo') %></div>
        </span>
      <% end %>
      <div class="sidebar-container">
        <span class="sidebar-text">
          <% if user_signed_in? %>
            <%= link_to "Accueil", root_path, class: "sidebar-link" %><br>
            <%= link_to "Mes formations", user_assignments_path(current_user.id), class: "sidebar-link" %><br>
            <% if current_user.status_customer? %>
              <%= link_to "Mon espace entreprise", company_path(current_user.company.id), class: "sidebar-link" %>
            <% end %>
            <% if current_user.status_administrator? %>
              <%= link_to "Mon espace entreprise", company_path(current_user.company.id), class: "sidebar-link" %>
              <%= link_to "Administrer Zorya", rails_admin_path(), class: "sidebar-link" %>
            <% else %>
            <% end %>
          <% end %>
        </span>
      </div>
      <!-- // END Sidebar Content -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en"
      dir="ltr"
      class="dark-mode">
  <head>
    <title>Zorya</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'spinkit', media: 'all' %>
    <%= favicon_link_tag asset_path('faviconZorya.png') %>
    <!-- Prevent the demo from appearing in search engines -->
    <meta name="robots"
              content="noindex">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700%7CRoboto:400,500%7CExo+2:600&display=swap"
              rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- Perfect Scrollbar -->
    <%= stylesheet_link_tag    'perfect-scrollbar', media: 'all' %>
    <!-- Material Design Icons -->
    <%= stylesheet_link_tag    'material-icons', media: 'all' %>
    <!-- Font Awesome Icons -->
    <%= stylesheet_link_tag    'fontawesome', media: 'all' %>
    <!-- App CSS -->
    <%= stylesheet_link_tag    'app', media: 'all' %>
    <!-- Dark Mode CSS -->
    <%= stylesheet_link_tag    'dark', media: 'all' %>
  </head>
  <body>
    <!-- Drawer Layout -->
    <div class="mdk-drawer-layout js-mdk-drawer-layout"
             data-push
             data-responsive-width="992px">
      <div class="mdk-drawer-layout__content page-content">
        <!-- BEFORE Page Content -->
        <!-- // END BEFORE Page Content -->
        <!-- Page Content -->
        <!-- Replace this with your page content -->
        <%= render 'layouts/navbar' %>
        <% if current_page?(root_path) %>
          <%= render 'layouts/header' %>
        <% elsif user_signed_in? && current_page?(current_user) %>
          <%= render 'layouts/profile_header' %>
        <% else %>
        <% end %>
        <!-- ALERT MSGS -->
        <% flash.each do |name, msg| %>
          <div class='alert alert-<%= name %> text-center'>
            <%= msg %>
          </div>
        <% end %>
        <!-- ALERT MSGS END -->
        <div class="container page__container flex d-flex my-32pt">
          <div class="" style="width: 100%">
            <span><%= yield %></span>
          </div>
        </div>
        <!-- // END Replace this with your page content -->
        <!-- // END Page Content -->
        <!-- Footer -->
        <%= render 'layouts/footer' %>
        <!-- // END Footer -->
      </div>
      <!-- // END drawer-layout__content -->
      <!-- Drawer -->
      <!-- // END Sidebar Content -->
      <% if user_signed_in? %>
        <%= render 'layouts/sidebar' %>
      <% end %>
      <!-- // END Drawer -->
    </div>
    <!-- jQuery -->
    <%= javascript_include_tag 'jquery.min' %>
    <!-- Bootstrap -->
    <%= javascript_include_tag 'bootstrap.min' %>
    <!-- Perfect Scrollbar -->
    <%= javascript_include_tag 'perfect-scrollbar' %>
    <!-- DOM Factory -->
    <%= javascript_include_tag 'dom-factory' %>
    <!-- MDK -->
    <%= javascript_include_tag 'material-design-kit' %>
    <!-- App JS -->
    <%= javascript_include_tag 'app' %>
    <!-- global app JS -->
    <%= javascript_include_tag 'application' %>
  </body>
</html>